server:
  port: 9090
spring:
  profiles:
    active: dev
  application:
    name: cabinet
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
jwt:
  tokenHeader: X-Token
  tokenHead: Bearer
  secret: hkustcabinetsecret7a8e18ad75bf457b9aa2714806a1bbe9 #JWT加解密使用的密钥
#  expiration: 300000
  expiration: 30000000
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
