server:
  port: 9090
spring:
  profiles:
    active: dev
  application:
    name: cabinet
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    default-property-inclusion: non_null
jwt:
  tokenHeader: X-Token
  tokenHead: Bearer
  secret: hkustcabinetsecret7a8e18ad75bf457b9aa2714806a1bbe9 #JWT加解密使用的密钥
  expirSc: 30000000
  expirMc: 30000000
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
